name: unittest

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: test
        run: make test
